### ISSUE TITLE
Dokumentáció

### ISSUE THREAD

**Issue by csomorbalazs** [BME-MIT-IET/2rulez-iet-2020#18]
> Minden egyes kiválasztott feladatról legyen egy-egy külön fájl: egy-két bekezdés az elvégzett munkáról, képernyőkép (ha releváns), eredmények és tanulságok összefoglalása.

Az egyes részfeladatokhoz tartozó dokumentáció a doc mappában található, mindenki azt dokumentálja, amiben a legaktívabban részt vett.

**Comment by kissbarnabas** [comment]
Jó lesz.
