### ISSUE TITLE
.git/config módosítása lokálisan mindenkinél

### ISSUE THREAD

**Issue by kissbarnabas** [BME-MIT-IET/2rulez-iet-2020#20]
A .git/config fájba az alábbi kiegészítést felvéve egy notebook commitolása esetén automatikusan megtörténik az outputok és az execution counterek clear-elése, így lefut az erre vonatkozó teszt.

 `[filter "strip-notebook-output"]
    clean = "jupyter nbconvert --ClearOutputPreprocessor.enabled=True --to=notebook --stdin --stdout --log-level=ERROR"`

**Comment by csomorbalazs** [comment]
Kész ✅

**Comment by bendicsekb** [comment]
Kész, köszi a tippet!

**Comment by nandorlengyel** [comment]
kész.
